### ISSUE TITLE
2 Bugs

### ISSUE THREAD

**Issue by mod000** [ChairPotato/gg-bot-issues#1]
1. Beim Ersten Starten des Bots wird man auf das Plot teleportiert und farmt dort. Danach kann muss man das Farmen kurz stoppen und wieder in der Farmwelt starten, dann ist es gefixt.
2. Fallen die Leben unter 5 Herzen, teleportiert man sich zwar zum Plot, allerdings werden die Items trotzdem in die Truhe gespammt. Danach läuft der Bot einige Blöcke weg und man wird wieder zur Kiste teleportiert. Das wiederholt sich (vermutlich weil die Leben nicht wieder ansteigen und deswegen dieser Safe, dass man zum Plot teleportiert wird, greift). Das Home wird dann auch nochmal auf dem plot gesetzt.
3. Ein Account hat nicht gegessen und die Items nicht abgelegt (Sollte ja normalerweise bei 9 Stacks sein) und selbst bei 10 Stacks ist nichts passiert. (Edit: Scheint auch bei einem anderen Account passiert zu sein und die Items werden auch nicht gedroppt)
4. Man bleibt in Wasser an Blöcken hängen.

**Comment by RealFinalCode** [comment]
Es sollten alle Probleme mit der neuen Version behoben sein. Allerdings kann ich noch nicht nachvollziehen was das Problem mit dem Essen sein soll... Es gibt dafür eig nur eine Möglichkeit und die wäre, dass das Inventar die ganze Zeit voll ist. Wenn das Problem nochmal auftritt bitte auf das Inventar achten.
