### ISSUE TITLE
Bugs der neuen Version

### ISSUE THREAD

**Issue by mod000** [ChairPotato/gg-bot-issues#2]
1. Nachdem man zum Plot teleportiert wurde, weil man unter 5 HP ist, wird man nicht wieder zurück in die Farmwelt teleportiert. (Vorschlag dazu: der Account isst auf dem Plot, sodass er wieder geheilt ist)
2. Ist kein richtiger Bug, aber es wäre gut, wenn der Bot nicht nur Cobblestone etc droppt, sondern auch alles andere, was keine Dias sind. Irgendwann ist sonst das Inventar mit den Items voll und deshalb isst der Account nicht mehr und geht nicht mehr zum Ablegen zum Plot.

**Comment by ChairPotato** [comment]
Bugs wurden soweit gefixt

**Comment by mod000** [comment]
Der 1. Bug ist wohl immer noch drin. 2 Mal hab ich gerade schon gesehen, wie die 2 verschiedene Accs unter 10 HP haben und sich dann zum Plot teleportieren. Von da aus ist nichts passiert, er wollte sich scheinbar wieder in die Farmwelt teleportieren, aber der Spamm Schutz hat das nicht zugelassen. Als ich dann manuell gegessen habe, hat er angefangen auf dem Plot zu farmen. 
Am sinnvollsten wäre es da denke ich, wenn auf dem Plot zum Healen gegessen wird und sobald man dann wieder >10 HP hat, sollte man wieder in die Farmwelt gehen.
